import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import {
  FaClipboardCheck,
  FaBook,
  FaCalendarAlt,
  FaUsers,
  FaArrowRight,
  FaSyncAlt,
} from "react-icons/fa";

import DashboardLayout from "../../layouts/DashboardLayout";
import PageHeader from "../../components/PageHeader";
import API_URL from "../../config/api";

import "../../styles/Dashboard.css";
import "../../styles/attendanceHistory.css";

function AttendanceHistory() {
  const [sessions, setSessions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    loadSessions();
  }, []);

  async function loadSessions() {
    try {
      setLoading(true);
      setError("");

      const user = JSON.parse(localStorage.getItem("user"));

      if (!user?.id) {
        throw new Error("Lecturer information could not be found.");
      }

      const response = await fetch(
        `${API_URL}/api/attendance/lecturer/${user.id}`,
        {
          headers: {
            Authorization: `Bearer ${localStorage.getItem("token")}`,
          },
        }
      );

      const data = await response.json();

      if (!response.ok) {
        throw new Error(
          data.message || "Failed to load attendance history."
        );
      }

      setSessions(data.sessions || []);
    } catch (error) {
      console.error("Error loading attendance history:", error);
      setError(error.message);
      setSessions([]);
    } finally {
      setLoading(false);
    }
  }

  function formatDate(date) {
    if (!date) return "N/A";

    return new Date(date).toLocaleDateString(undefined, {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  }

  function formatTime(date) {
    if (!date) return "N/A";

    return new Date(date).toLocaleTimeString(undefined, {
      hour: "2-digit",
      minute: "2-digit",
    });
  }

  function getStatusClass(status) {
    if (!status) return "status-default";

    const normalizedStatus = status.toLowerCase();

    if (
      normalizedStatus === "active" ||
      normalizedStatus === "open"
    ) {
      return "status-active";
    }

    if (
      normalizedStatus === "closed" ||
      normalizedStatus === "completed"
    ) {
      return "status-completed";
    }

    if (
      normalizedStatus === "expired"
    ) {
      return "status-expired";
    }

    return "status-default";
  }

  return (
    <DashboardLayout
      title="Attendance History"
      role="lecturer"
    >
      <div className="attendance-history-page">

        {/* =========================
            PAGE HEADER
           ========================= */}

        <PageHeader
          title="Attendance History"
          subtitle="Review attendance sessions generated for your assigned courses."
        />

        {/* =========================
            SUMMARY
           ========================= */}

        <div className="attendance-history-summary">

          <div className="attendance-summary-card">
            <div className="attendance-summary-icon blue">
              <FaClipboardCheck />
            </div>

            <div>
              <span>Total Sessions</span>
              <strong>{sessions.length}</strong>
            </div>
          </div>

          <div className="attendance-summary-card">
            <div className="attendance-summary-icon green">
              <FaBook />
            </div>

            <div>
              <span>Courses</span>
              <strong>
                {
                  new Set(
                    sessions
                      .map(
                        (session) =>
                          session.course?._id ||
                          session.course?.courseCode
                      )
                      .filter(Boolean)
                  ).size
                }
              </strong>
            </div>
          </div>

          <div className="attendance-summary-card">
            <div className="attendance-summary-icon orange">
              <FaUsers />
            </div>

            <div>
              <span>Students Recorded</span>
              <strong>
                {sessions.reduce(
                  (total, session) =>
                    total + (session.totalStudents || 0),
                  0
                )}
              </strong>
            </div>
          </div>

        </div>

        {/* =========================
            ATTENDANCE SECTION
           ========================= */}

        <div className="attendance-history-section">

          <div className="attendance-history-section-header">

            <div>
              <span className="attendance-section-label">
                ATTENDANCE MANAGEMENT
              </span>

              <h2>
                Attendance Sessions
              </h2>

              <p>
                All attendance sessions generated by you.
              </p>
            </div>

            <button
              type="button"
              className="attendance-refresh-btn"
              onClick={loadSessions}
              disabled={loading}
            >
              <FaSyncAlt
                className={loading ? "spinning" : ""}
              />

              {loading ? "Refreshing..." : "Refresh"}
            </button>

          </div>

          {/* =========================
              LOADING
             ========================= */}

          {loading && (
            <div className="attendance-history-empty">

              <div className="attendance-loading-icon">
                <FaClipboardCheck />
              </div>

              <h3>
                Loading attendance history...
              </h3>

              <p>
                Please wait while we retrieve your attendance sessions.
              </p>

            </div>
          )}

          {/* =========================
              ERROR
             ========================= */}

          {!loading && error && (
            <div className="attendance-history-empty error-state">

              <div className="attendance-loading-icon">
                <FaClipboardCheck />
              </div>

              <h3>
                Unable to load attendance history
              </h3>

              <p>
                {error}
              </p>

              <button
                type="button"
                className="attendance-retry-btn"
                onClick={loadSessions}
              >
                <FaSyncAlt />
                Try Again
              </button>

            </div>
          )}

          {/* =========================
              EMPTY
             ========================= */}

          {!loading &&
            !error &&
            sessions.length === 0 && (
              <div className="attendance-history-empty">

                <div className="attendance-loading-icon">
                  <FaClipboardCheck />
                </div>

                <h3>
                  No attendance sessions yet
                </h3>

                <p>
                  Attendance sessions that you generate
                  will appear here.
                </p>

                <Link
                  to="/lecturer/start-attendance"
                  className="attendance-start-btn"
                >
                  <FaClipboardCheck />
                  Start Attendance
                  <FaArrowRight />
                </Link>

              </div>
            )}

          {/* =========================
              DESKTOP TABLE
             ========================= */}

          {!loading &&
            !error &&
            sessions.length > 0 && (
              <div className="attendance-table-wrapper">

                <table className="attendance-history-table">

                  <thead>
                    <tr>
                      <th>COURSE</th>
                      <th>CODE</th>
                      <th>STATUS</th>
                      <th>STUDENTS</th>
                      <th>DATE</th>
                      <th>ACTION</th>
                    </tr>
                  </thead>

                  <tbody>

                    {sessions.map((session) => (

                      <tr key={session._id}>

                        {/* COURSE */}

                        <td>
                          <div className="attendance-course-cell">

                            <div className="attendance-course-icon">
                              <FaBook />
                            </div>

                            <div>
                              <strong>
                                {session.course?.courseName ||
                                  "Unknown Course"}
                              </strong>

                              {session.course?.title &&
                                session.course.title !==
                                  session.course.courseName && (
                                  <small>
                                    {session.course.title}
                                  </small>
                                )}
                            </div>

                          </div>
                        </td>

                        {/* CODE */}

                        <td>
                          <span className="course-code">
                            {session.course?.courseCode ||
                              "N/A"}
                          </span>
                        </td>

                        {/* STATUS */}

                        <td>
                          <span
                            className={`attendance-status ${getStatusClass(
                              session.status
                            )}`}
                          >
                            <span className="status-dot"></span>
                            {session.status || "Unknown"}
                          </span>
                        </td>

                        {/* STUDENTS */}

                        <td>
                          <div className="student-count">

                            <FaUsers />

                            <strong>
                              {session.totalStudents || 0}
                            </strong>

                            <span>
                              recorded
                            </span>

                          </div>
                        </td>

                        {/* DATE */}

                        <td>
                          <div className="attendance-date">

                            <FaCalendarAlt />

                            <div>
                              <strong>
                                {formatDate(
                                  session.startTime
                                )}
                              </strong>

                              <small>
                                {formatTime(
                                  session.startTime
                                )}
                              </small>
                            </div>

                          </div>
                        </td>

                        {/* ACTION */}

                        <td>
                          <Link
                            to={`/lecturer/attendance/${session._id}`}
                            className="attendance-view-btn"
                          >
                            View
                            <FaArrowRight />
                          </Link>
                        </td>

                      </tr>

                    ))}

                  </tbody>

                </table>

              </div>
            )}

        </div>

      </div>
    </DashboardLayout>
  );
}

export default AttendanceHistory;