import { FaQrcode,
  FaUsers,
  FaClipboardCheck,
  FaChartBar,
} from "react-icons/fa";

import DashboardLayout from "../../layouts/DashboardLayout";
import DashboardCard from "../../components/DashboardCard";


function Dashboard() {
  const user = JSON.parse(localStorage.getItem("user"));

  return (
    <DashboardLayout
      title="Lecturer Dashboard"
      role="lecturer"
    >
      <div className="welcome-section">
        <h1>
          Welcome back, {user?.name || "Lecturer"} 👋
        </h1>

        <p>
          Generate attendance QR codes and monitor student attendance.
        </p>
      </div>

      <div className="cards">
        <DashboardCard
          title="QR Sessions"
          value="0"
          icon={<FaQrcode />}
          color="#0d6efd"
        />

        <DashboardCard
          title="Students Present"
          value="0"
          icon={<FaUsers />}
          color="#20c997"
        />

        <DashboardCard
          title="Attendance Records"
          value="0"
          icon={<FaClipboardCheck />}
          color="#fd7e14"
        />

        <DashboardCard
          title="Attendance Rate"
          value="0%"
          icon={<FaChartBar />}
          color="#6f42c1"
        />
      </div>

      <div className="dashboard-section">
        <div className="section-header">
          <div>
            <h2>Recent Attendance Sessions</h2>
            <p>Attendance sessions generated by you will appear here.</p>
          </div>
        </div>

        <div className="empty-state">
          <FaClipboardCheck />

          <h3>No attendance session yet</h3>

          <p>
            Generate a QR code to start recording student attendance.
          </p>
        </div>
      </div>
    </DashboardLayout>
  );
}

export default Dashboard;